
@baseUrl = http://127.0.0.1:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImFkbWluIiwidXNlcklkIjoxLCJpYXQiOjE3MzA5NTczMTIsImV4cCI6MTczMTA0MzcxMn0.GCX_zra2o4T22b3kuDPOXEgwayDLSjaqy0rzwG4y9dA
@wxToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcGVuaWQiOiJvV09PZjdTQ0pqZGw0dkxsTlV0S3hXaUZ2OUxZIiwiaWF0IjoxNzMxNjUzMjI2LCJleHAiOjE3MzE3Mzk2MjZ9.7KlmTJvh4XjjMo0kaocILURfZ7WxgTyg_u9cXcO2TgE
###  登录
POST {{baseUrl}}/api/admin/login HTTP/1.1
content-type: application/json

{
    "userName": "xtdgjhch",
    "password": "xtdgjhch1016"
}

### 获取admin 用户信息
GET {{baseUrl}}/api/admin/userInfo HTTP/1.1
Cookie: token={{token}}


### 获取视频列表
GET {{baseUrl}}/api/videos HTTP/1.1
Cookie: token={{token}}


###  视频详细
GET {{baseUrl}}/api/videos/1 HTTP/1.1
Cookie: token={{token}}

###  logs
GET {{baseUrl}}/api/logs HTTP/1.1
Cookie: token={{token}}


###  add logs
POST {{baseUrl}}/api/logs HTTP/1.1
Content-Type: application/json
Cookie: token={{wxToken}}

{
    "id": 13
}

###  get all likes
GET {{baseUrl}}/api/likes HTTP/1.1
Cookie: token={{token}}


###  add likes
POST {{baseUrl}}/api/likes HTTP/1.1
Content-Type: application/json
Cookie: token={{wxToken}}

{
    "id": 13
}

###  delete likes
DELETE {{baseUrl}}/api/likes HTTP/1.1
Content-Type: application/json
Cookie: token={{wxToken}}

{
    "id": 2
}