
@baseUrl = http://127.0.0.1:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImFkbWluIiwidXNlcklkIjoxLCJpYXQiOjE3MzA5NTczMTIsImV4cCI6MTczMTA0MzcxMn0.GCX_zra2o4T22b3kuDPOXEgwayDLSjaqy0rzwG4y9dA

@wxToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcGVuaWQiOiJvV09PZjdTQ0pqZGw0dkxsTlV0S3hXaUZ2OUxZIiwiaWF0IjoxNzMxOTExMzk5LCJleHAiOjE3MzE5OTc3OTl9.DB80pR-2s_PD5VupNqV8AgspB6F0TUiBCWqjVv4wn38
###  登录
POST {{baseUrl}}/api/admin/login HTTP/1.1
content-type: application/json

{
    "email": "aaa@qq.com",
    "password": "123456",
    "captchaId": "36f8f16b-a225-431f-81c5-7cd9f0a6e38e",
    "captchaText": "Wmuy"
}

### 获取 当前登录 admin 用户信息
GET {{baseUrl}}/api/admin/userInfo HTTP/1.1

### 获取所有admin 用户
GET {{baseUrl}}/api/admin/users HTTP/1.1

### 获取视频列表
GET {{baseUrl}}/api/videos HTTP/1.1
Cookie: token={{token}}


###  视频详细
GET {{baseUrl}}/api/videos/1 HTTP/1.1
Cookie: token={{token}}

###  logs
GET {{baseUrl}}/api/logs HTTP/1.1
Cookie: token={{token}}


###  add logs
POST {{baseUrl}}/api/logs HTTP/1.1
Content-Type: application/json
Cookie: token={{wxToken}}

{
    "id": 13
}

###  get all likes
GET {{baseUrl}}/api/likes HTTP/1.1
Cookie: token={{token}}


###  add likes
POST {{baseUrl}}/api/likes HTTP/1.1
Content-Type: application/json
token: {{wxToken}}

{
    "id": 13
}

###  delete likes
DELETE {{baseUrl}}/api/likes HTTP/1.1
Content-Type: application/json
token: {{wxToken}}

{
    "id": 1
}

###  get all user
GET {{baseUrl}}/api/users HTTP/1.1
Cookie: token={{token}}

###  get all user_login_logs
GET {{baseUrl}}/api/user-login-logs HTTP/1.1
Cookie: token={{token}}


### 验证用户名是否可用
GET {{baseUrl}}/api/admin/check-availability?email=aaa@qq.com HTTP/1.1
Cookie: token={{token}}

### 生成验证码
GET {{baseUrl}}/api/admin/captcha HTTP/1.1
Cookie: token={{token}}

### 获取所有roles
GET {{baseUrl}}/api/roles HTTP/1.1
Cookie: token={{token}}

###  add roles
POST {{baseUrl}}/api/roles HTTP/1.1
Content-Type: application/json
Cookie: token={{wxToken}}

{
    "name": "admin",
    "description": "管理员",
    "permissions": [15, 16]
}

###  update roles
PUT {{baseUrl}}/api/roles/51 HTTP/1.1
Content-Type: application/json
Cookie: token={{wxToken}}

{
    "name": "user",
    "description": "普通用户",
    "permissions": []
}

### 删除role
DELETE {{baseUrl}}/api/roles/3 HTTP/1.1
Cookie: token={{token}}

### 获取所有permissions
GET {{baseUrl}}/api/permissions HTTP/1.1
Cookie: token={{token}}

###  add permissions
POST {{baseUrl}}/api/permissions HTTP/1.1
Content-Type: application/json
Cookie: token={{wxToken}}

{
    "name": "delete",
    "description": "删除功能"
}

###  update permissions
PUT {{baseUrl}}/api/permissions/1 HTTP/1.1
Content-Type: application/json
Cookie: token={{wxToken}}

{
    "name": "",
    "description": "超级管理员"
}

### 删除 permissions
DELETE {{baseUrl}}/api/permissions/1 HTTP/1.1
Cookie: token={{token}}


### 发送验证码到邮件
GET {{baseUrl}}/api/admin/send-captcha2email?email=ac@qq.com HTTP/1.1
Cookie: token={{token}}


###  admin 用户注册
POST {{baseUrl}}/api/admin/register HTTP/1.1
Content-Type: application/json
Cookie: token={{token}}

{
    "email": "ac@qq.com",
    "password": "123456",
    "captchaText": "ur81",
    "roles": [51, 52]
}