
@baseUrl = http://127.0.0.1:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImFkbWluIiwidXNlcklkIjoxLCJpYXQiOjE3MzA5NTczMTIsImV4cCI6MTczMTA0MzcxMn0.GCX_zra2o4T22b3kuDPOXEgwayDLSjaqy0rzwG4y9dA

@wxToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcGVuaWQiOiJvV09PZjdTQ0pqZGw0dkxsTlV0S3hXaUZ2OUxZIiwiaWF0IjoxNzMxOTExMzk5LCJleHAiOjE3MzE5OTc3OTl9.DB80pR-2s_PD5VupNqV8AgspB6F0TUiBCWqjVv4wn38
###  登录
POST {{baseUrl}}/api/admin/login HTTP/1.1
content-type: application/json

{
    "userName": "admin",
    "password": "123456"
}

### 获取admin 用户信息
GET {{baseUrl}}/api/admin/userInfo HTTP/1.1


### 获取视频列表
GET {{baseUrl}}/api/videos HTTP/1.1
Cookie: token={{token}}


###  视频详细
GET {{baseUrl}}/api/videos/1 HTTP/1.1
Cookie: token={{token}}

###  logs
GET {{baseUrl}}/api/logs HTTP/1.1
Cookie: token={{token}}


###  add logs
POST {{baseUrl}}/api/logs HTTP/1.1
Content-Type: application/json
Cookie: token={{wxToken}}

{
    "id": 13
}

###  get all likes
GET {{baseUrl}}/api/likes HTTP/1.1
Cookie: token={{token}}


###  add likes
POST {{baseUrl}}/api/likes HTTP/1.1
Content-Type: application/json
token: {{wxToken}}

{
    "id": 13
}

###  delete likes
DELETE {{baseUrl}}/api/likes HTTP/1.1
Content-Type: application/json
token: {{wxToken}}

{
    "id": 1
}

###  get all user
GET {{baseUrl}}/api/users HTTP/1.1
Cookie: token={{token}}

###  get all user_login_logs
GET {{baseUrl}}/api/user-login-logs HTTP/1.1
Cookie: token={{token}}


### 验证用户名是否可用
GET {{baseUrl}}/api/admin/check-availability?userName=admin HTTP/1.1
Cookie: token={{token}}

### 生成验证码
GET {{baseUrl}}/api/admin/captcha HTTP/1.1
Cookie: token={{token}}

### 生成验证码
POST {{baseUrl}}/api/admin/register HTTP/1.1
Content-Type: application/json

{
    "userName": "aaa",
    "password": "123455",
    "captchaId": "1",
    "captchaText": "111",
    "email": "3333"
}